version: '3.8'

services:
  # Spring Boot Backend
  neural-synth-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MYSQL_URL=jdbc:mysql://mysql:3306/NEURAL_SYNTH
      - MONGODB_URI=mongodb://mongodb:27017/neural_synth
      - MODEL_SERVER_URL=http://host.docker.internal:3000
    depends_on:
      - mysql
      - mongodb
    networks:
      - neural-synth-network
    restart: unless-stopped

  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: NEURAL_SYNTH
      MYSQL_USER: readwrite
      MYSQL_PASSWORD: readwrite
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/db/mysql/init_neural_synth.sql:/docker-entrypoint-initdb.d/init_neural_synth.sql
    networks:
      - neural-synth-network
    restart: unless-stopped

  # MongoDB
  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_DATABASE: neural_synth
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./src/main/resources/db/mongo/audio_request_collection_init.js:/docker-entrypoint-initdb.d/audio_request_collection_init.js:ro
    networks:
      - neural-synth-network
    restart: unless-stopped

volumes:
  mysql_data:
  mongodb_data:

networks:
  neural-synth-network:
    driver: bridge 